---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    # TASK 1
    - name: Install postgresql-server
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.package:
        name: postgresql-server
        state: present
    
    
    

    # TASK 2
    # Ansible Lightspeed used an easy-to-understand natural language prompt and suggested the correct, more complex PostgreSQL CLI command to initiate the database.
    # Ansible Lightspeed used best practices and kept the task idempotent by including creates: /var/lib/pgsql/data/postgresql.conf in the suggestion.
    - name: Run postgresql setup command
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.command: /usr/pgsql-12/bin/postgresql-setup --initdb
      become: true
      become_user: postgres
    

    

    # TASK 3
    # Ansible Lightspeed used natural language prompt and added state: started and enabled: true module arguments based on Start and enable... in the Ansible task description.
    # - name: Start and enable postgresql service
